### PR TITLE
domvm implementation

### PR DESCRIPTION
**Pull request by leeoniya**
this includes a fetch polyfill since support in browsers is still spottier than Promise, rAF and history.

### CODE REVIEW

**Comment by koglerjs** [comment]
Ah, you even chose a color!  Lovely.  domvm.threaditjs.com is up, I'll have to get around to fixing the docs at some point.

**Comment by leeoniya** [comment]
> I'll have to get around to fixing the docs at some point.

Thanks, no rush.

**Comment by leeoniya** [comment]
@koglerjs 

There have been some breaking changes recently in the lib and possibly more until 1.0 slated for 4/1. The perf remain the same but various semantics/signatures are still being refined. I'm keeping a working impl updated in the `domvm` repo and will make another threaditjs PR once things have settled.

thanks!

**Comment by koglerjs** [comment]
Sounds good!  Nothing's stopping the current version from running.  I haven't had much time to move the project forward recently, but I'll be sure to approve the PR once it lands.

**Pull request merged**
